version: '2'

services:
  survey:
    build:
      context: .
    restart: on-failure:5
    volumes:
      - ./survey:/survey
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo_database
    links:
      - "mongo_database:mongodb"

  mongo_database:
    image: mongo:4.2
    hostname: mongodb
    restart: on-failure:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./initdb.d/:/docker-entrypoint-initdb.d/
      - ./data/db/:/data/db/
      - ./data/log/:/var/log/mongodb/
