version: '3'

services:
  survey_back:
    build: 
      context: .
    restart: on-failure:5
    volumes:
      - ./survey:/app
    env_file:
      - ./.flaskenv
    networks:
      - traefik
    depends_on:
      - mongo_database
    links:
      - "mongo_database:mongo_db"
    labels:
      - traefik.enable=true
      - traefik.http.tls=${TLS}
      - traefik.http.routers.survey_back.rule=Host(${DOMAINE_NAME})
      - traefik.http.services.survey_back_service.loadbalancer.server.port=5000

  mongo_database:
    image: mongo:4.2
    ports:
      - 27017:27017
    env_file: mongo.conf
    restart: on-failure:5
    command: mongod --auth
    networks:
      - traefik
    volumes:
      - ./data:/db

networks:
  traefik:
    external: true

