version: '2'

services:
  survey:
    build:
      context: .
    restart: on-failure:5
    volumes:
      - ./survey:/survey
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - "db:db"

  db:
    image: postgres:9.6
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    #volumes:
      #- ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080
