FROM tiangolo/uwsgi-nginx:python3.8-alpine

LABEL MAINTAINER="Rami sfari <rami2sfari@gmail.com>"


COPY ./entrypoint.sh ./requirements.txt /

# Install Dependencies
RUN ["pip", "install", "-r", "/requirements.txt"]

ENV LISTEN_PORT 5000

EXPOSE 5000

# Create New user & group
RUN groupadd -r uswgi && useradd -r -g uswgi uswgi
USER uswgi
