version: '3'

services:
  survey_deploy:
    build:
      context: .
    restart: on-failure:5
    volumes:
      - ./survey:/survey
    env_file:
      - ./.env
    networks:
      - traefik
    depends_on:
      - db
    links:
      - "db:db"
    labels:
      - traefik.enable=true
      - traefik.http.tls=true
      - traefik.http.routers.survey_back.rule=Host("${SITE_DOMAINE_NAME}")
      - traefik.http.services.survey_back_service.loadbalancer.server.port=5000

  db:
    image: postgres:9.6
    restart: on-failure:5
    networks:
      - traefik
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: on-failure:5
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.tls=true
      - traefik.http.routers.adminer.rule=Host("${ADMINER_DOMAINE_NAME}")
      - traefik.http.services.adminer_service.loadbalancer.server.port=8080

networks:
  traefik:
    external: true

