version: '2'

services:
  survey_back:
    container_name: survey_back
    image: predictanalyse/survey-back:latest
    restart: on-failure:5
    env_file:
      - ./.env
    depends_on:
      - mongo_database
    links:
      - "mongo_database:mongo_db"
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.survey_deploy.rule=Host(`back.questionnaire-a.tk`)
      - traefik.http.services.survey.loadbalancer.server.port=5000

  mongo_database:
    image: mongo:4.2
    ports:
      - 27017:27017
    env_file: mongo.conf
    restart: on-failure:5
    networks:
      - traefik
    command: mongod --auth
    volumes:
      - ./data:/db

networks:
  traefik:
    external: true
