version: '3'

services:
  survey_backend_deploy:
    image: predictanalyse/survey-back
    restart: on-failure:5
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - "db:db"
    labels:
      - traefik.enable=true
      - traefik.http.routers.survey_back.tls=${TLS}
      - traefik.http.routers.survey_back.rule=Host("${SITE_DOMAINE_NAME}")
      - traefik.http.services.survey_back_service.loadbalancer.server.port=5000

  db:
    image: postgres:9.6
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data
    labels:
      - traefik.enable=false

  adminer:
    image: adminer
    restart: on-failure:5
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.tls=${TLS}
      - traefik.http.routers.adminer.rule=Host("${ADMINER_DOMAINE_NAME}")
      - traefik.http.services.adminer_service.loadbalancer.server.port=8080

  axigen: 
    image: axigen/axigen
    restart: on-failure:5
    volumes:
      - ./mail:/var/opt/axigen 
    ports: 
      - 9443:9443 
      - 993:993 
      - 995:995 
      - 25:25 
      - 465:465
      - 7000:7000
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.tls=${TLS}
      - traefik.http.routers.adminer.rule=Host("${MAIL_DOMAINE_NAME}")
      - traefik.http.services.adminer_service.loadbalancer.server.port=9000


networks:
  default:
    external:
      name: traefik

