"""empty message

Revision ID: 11fd60a90030
Revises: 53a8af340bb6
Create Date: 2020-08-23 22:08:47.692141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fd60a90030'
down_revision = '53a8af340bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('employee_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_pk'], ['baseuser.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('question',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=255), nullable=True),
    sa.Column('questionnaire_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_pk'], ['questionnaire.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('questionnaire')
    # ### end Alembic commands ###
