"""empty message

Revision ID: 2150fc8759dc
Revises: 660e2c1018ab
Create Date: 2020-08-20 23:23:56.451404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2150fc8759dc'
down_revision = '660e2c1018ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseuser', sa.Column('department_pk', sa.Integer(), nullable=True))
    op.add_column('baseuser', sa.Column('professional_email', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'baseuser', ['professional_email'])
    op.create_foreign_key(None, 'baseuser', 'department', ['department_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'baseuser', type_='foreignkey')
    op.drop_constraint(None, 'baseuser', type_='unique')
    op.drop_column('baseuser', 'professional_email')
    op.drop_column('baseuser', 'department_pk')
    # ### end Alembic commands ###
