"""empty message

Revision ID: 53a8af340bb6
Revises: f25be2b80db1
Create Date: 2020-08-21 01:12:19.902866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a8af340bb6'
down_revision = 'f25be2b80db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('baseuser_question_history_pk_fkey', 'baseuser', type_='foreignkey')
    op.drop_table('questionhistory')
    op.add_column('baseuser', sa.Column('question_history', sa.Text(), nullable=True))
    op.drop_column('baseuser', 'question_history_pk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseuser', sa.Column('question_history_pk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('baseuser_question_history_pk_fkey', 'baseuser', 'questionhistory', ['question_history_pk'], ['pk'])
    op.drop_column('baseuser', 'question_history')
    op.create_table('questionhistory',
    sa.Column('current_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selected_body_area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_Question', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('answered_questions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_args', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('pk', name='questionhistory_pkey')
    )
    # ### end Alembic commands ###
