"""empty message

Revision ID: 660e2c1018ab
Revises: bf0ef4968413
Create Date: 2020-08-20 16:59:10.711408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660e2c1018ab'
down_revision = 'bf0ef4968413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitationinfo_invitation_pk_fkey', 'invitationinfo', type_='foreignkey')
    op.create_foreign_key(None, 'invitationinfo', 'baseinvitation', ['invitation_pk'], ['pk'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitationinfo', type_='foreignkey')
    op.create_foreign_key('invitationinfo_invitation_pk_fkey', 'invitationinfo', 'baseinvitation', ['invitation_pk'], ['pk'])
    # ### end Alembic commands ###
