"""empty message

Revision ID: 6e33a77848f2
Revises: c152a53b7624
Create Date: 2020-08-19 10:48:18.226120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e33a77848f2'
down_revision = 'c152a53b7624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionhistory',
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('selected_body_area', sa.Text(), nullable=True),
    sa.Column('current_Question', sa.Integer(), nullable=True),
    sa.Column('scores', sa.Text(), nullable=True),
    sa.Column('answered_questions', sa.Text(), nullable=True),
    sa.Column('extra_args', sa.Text(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('department',
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_pk'], ['company.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('invitationinfo',
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('invitation_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invitation_pk'], ['baseinvitation.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.add_column('baseinvitation', sa.Column('department_pk', sa.Integer(), nullable=True))
    op.drop_constraint('baseinvitation_email_key', 'baseinvitation', type_='unique')
    op.drop_constraint('baseinvitation_company_pk_fkey', 'baseinvitation', type_='foreignkey')
    op.create_foreign_key(None, 'baseinvitation', 'department', ['department_pk'], ['pk'])
    op.drop_column('baseinvitation', 'email')
    op.drop_column('baseinvitation', 'full_name')
    op.drop_column('baseinvitation', 'company_pk')
    op.add_column('baseuser', sa.Column('question_history_pk', sa.Integer(), nullable=True))
    op.drop_constraint('baseuser_company_pk_fkey', 'baseuser', type_='foreignkey')
    op.create_foreign_key(None, 'baseuser', 'questionhistory', ['question_history_pk'], ['pk'])
    op.drop_column('baseuser', 'company_pk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseuser', sa.Column('company_pk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'baseuser', type_='foreignkey')
    op.create_foreign_key('baseuser_company_pk_fkey', 'baseuser', 'company', ['company_pk'], ['pk'])
    op.drop_column('baseuser', 'question_history_pk')
    op.add_column('baseinvitation', sa.Column('company_pk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('baseinvitation', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('baseinvitation', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'baseinvitation', type_='foreignkey')
    op.create_foreign_key('baseinvitation_company_pk_fkey', 'baseinvitation', 'company', ['company_pk'], ['pk'])
    op.create_unique_constraint('baseinvitation_email_key', 'baseinvitation', ['email'])
    op.drop_column('baseinvitation', 'department_pk')
    op.drop_table('invitationinfo')
    op.drop_table('department')
    op.drop_table('questionhistory')
    # ### end Alembic commands ###
