"""empty message

Revision ID: 789591058917
Revises: 64068cbe6c5d
Create Date: 2020-07-28 19:13:31.639666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789591058917'
down_revision = '64068cbe6c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseuser', sa.Column('medical_record_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'baseuser', 'medicalrecord', ['medical_record_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'baseuser', type_='foreignkey')
    op.drop_column('baseuser', 'medical_record_pk')
    # ### end Alembic commands ###
