"""empty message

Revision ID: 799849f84267
Revises: 11fd60a90030
Create Date: 2020-09-06 04:36:38.733187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799849f84267'
down_revision = '11fd60a90030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('descriptions', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('questionnaire_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_pk'], ['questionnaire.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.add_column('question', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('question', sa.Text(), nullable=True))
    op.drop_column('question', 'name')
    op.drop_column('question', 'question_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('question', 'question')
    op.drop_column('question', 'answer')
    op.drop_table('score')
    # ### end Alembic commands ###
