"""empty message

Revision ID: 98399a8190a7
Revises: 
Create Date: 2020-07-26 11:58:52.443478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98399a8190a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('universal_name', sa.String(length=150), nullable=True),
    sa.Column('company_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('employee_count_range', sa.String(length=100), nullable=True),
    sa.Column('specialities', sa.String(length=150), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('founded_year', sa.String(length=150), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('medicalrecord',
    sa.Column('height', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.String(length=200), nullable=True),
    sa.Column('medical_history', sa.String(length=200), nullable=True),
    sa.Column('chronic_illness', sa.String(length=200), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('baseinvitation',
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.Column('is_created', sa.Boolean(), nullable=True),
    sa.Column('company_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_pk'], ['company.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('baseuser',
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('invitation_pk', sa.Integer(), nullable=True),
    sa.Column('company_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('_AccountMixin__hashed_password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_pk'], ['company.pk'], ),
    sa.ForeignKeyConstraint(['invitation_pk'], ['baseinvitation.pk'], ),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('baseuser')
    op.drop_table('baseinvitation')
    op.drop_table('medicalrecord')
    op.drop_table('company')
    # ### end Alembic commands ###
