"""empty message

Revision ID: b747dc5d21ab
Revises: 799849f84267
Create Date: 2020-09-06 21:06:59.906168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b747dc5d21ab'
down_revision = '799849f84267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questioncategory',
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('questionnaire_pk', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_pk'], ['questionnaire.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk')
    )
    op.drop_table('score')
    op.add_column('question', sa.Column('category_pk', sa.Integer(), nullable=True))
    op.drop_constraint('question_questionnaire_pk_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'questioncategory', ['category_pk'], ['pk'], ondelete='CASCADE')
    op.drop_column('question', 'questionnaire_pk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('questionnaire_pk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_questionnaire_pk_fkey', 'question', 'questionnaire', ['questionnaire_pk'], ['pk'], ondelete='CASCADE')
    op.drop_column('question', 'category_pk')
    op.create_table('score',
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descriptions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('questionnaire_pk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pk', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_pk'], ['questionnaire.pk'], name='score_questionnaire_pk_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pk', name='score_pkey')
    )
    op.drop_table('questioncategory')
    # ### end Alembic commands ###
