"""empty message

Revision ID: bf0ef4968413
Revises: 6a3542135652
Create Date: 2020-08-20 12:35:44.157590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf0ef4968413'
down_revision = '6a3542135652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseinvitation', sa.Column('company_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'baseinvitation', 'company', ['company_pk'], ['pk'])
    op.drop_column('baseuser', 'birthday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseuser', sa.Column('birthday', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'baseinvitation', type_='foreignkey')
    op.drop_column('baseinvitation', 'company_pk')
    # ### end Alembic commands ###
