"""empty message

Revision ID: c152a53b7624
Revises: 789591058917
Create Date: 2020-07-28 19:27:58.063853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c152a53b7624'
down_revision = '789591058917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalrecord', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('medicalrecord', sa.Column('home_work', sa.Integer(), nullable=True))
    op.add_column('medicalrecord', sa.Column('profession', sa.String(length=200), nullable=True))
    op.add_column('medicalrecord', sa.Column('sexe', sa.Integer(), nullable=True))
    op.add_column('medicalrecord', sa.Column('tall', sa.String(length=50), nullable=True))
    op.drop_column('medicalrecord', 'chronic_illness')
    op.drop_column('medicalrecord', 'medical_history')
    op.drop_column('medicalrecord', 'weight')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicalrecord', sa.Column('weight', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('medicalrecord', sa.Column('medical_history', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('medicalrecord', sa.Column('chronic_illness', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('medicalrecord', 'tall')
    op.drop_column('medicalrecord', 'sexe')
    op.drop_column('medicalrecord', 'profession')
    op.drop_column('medicalrecord', 'home_work')
    op.drop_column('medicalrecord', 'age')
    # ### end Alembic commands ###
