"""empty message

Revision ID: c9c46ac51332
Revises: b747dc5d21ab
Create Date: 2020-10-02 23:09:01.918010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c46ac51332'
down_revision = 'b747dc5d21ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('area', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'area')
    # ### end Alembic commands ###
