"""empty message

Revision ID: f25be2b80db1
Revises: 2150fc8759dc
Create Date: 2020-08-20 23:49:43.470695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25be2b80db1'
down_revision = '2150fc8759dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseinvitation', sa.Column('is_expired', sa.Boolean(), nullable=True))
    op.drop_column('baseinvitation', 'is_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseinvitation', sa.Column('is_created', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('baseinvitation', 'is_expired')
    # ### end Alembic commands ###
