"""
Stats Constants

Categories :
"""
PHYSIOTHERAPY="PHYSIOTHERAPY"
ERGONOMICS="ERGONOMICS"
MEDICINE="MEDICINE"
PSYCHOLOGY="PSYCHOLOGY"
COACH="COACH"
OSTEOPATHY="OSTEOPATHY"
STOPP_WORKING="STOPP_WORKING"



"""
Stats Constants

Area :
"""
HEADACHE = 'HEADACHE'
CERVICAL = 'SHOULDERS'
BACK_THORAX ='BACK_THORAX'
ELBOW_WIRST_HAND = 'ABDOMINAL_PAIN'
LUMBAR_BUTTOCKS = 'LUMBAR_BUTTOCKS'
HIP =  'HIP'
KNEES ='KNEES'
LEG_FOOT = 'LEG_FOOT'
