"""
Stats Constants

Categories :
"""
PHYSIOTHERAPY="PHYSIOTHERAPY"
ERGONOMICS="ERGONOMICS"
MEDICINE="MEDICINE"
PSYCHOLOGY="PSYCHOLOGY"
COACH="COACH"
OSTEOPATHY="OSTEOPATHY"
STOPP_WORKING="STOPP_WORKING"
